name: Solve D2D

on:
  push:
    branches:
    - "main"
    paths-ignore:
    - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-6:
    name: 6-customer problems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: ["6.10.1", "6.10.2", "6.10.3", "6.10.4", "6.20.1", "6.20.2", "6.20.3", "6.20.4", "6.5.1", "6.5.2", "6.5.3", "6.5.4"]
        drone-config-mapping: ["0 0 0 0", "1 1 1 1", "2 2 2 2", "3 3 3 3"]
        energy-mode: ["linear", "non-linear", "endurance"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run optimizer (1)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-1.json" \
          --extra run-1

      - name: Run optimizer (2)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-2.json" \
          --extra run-2

      - name: Run optimizer (3)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-3.json" \
          --extra run-3

      - name: Run optimizer (4)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-4.json" \
          --extra run-4

      - name: Run optimizer (5)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-5.json" \
          --extra run-5

      - name: Run optimizer (6)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-6.json" \
          --extra run-6

      - name: Run optimizer (7)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-7.json" \
          --extra run-7

      - name: Run optimizer (8)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-8.json" \
          --extra run-8

      - name: Run optimizer (9)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-9.json" \
          --extra run-9

      - name: Run optimizer (10)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-10.json" \
          --extra run-10

      - name: Upload solutions
        uses: actions/upload-artifact@v3
        with:
          name: d2d-summary
          path: output-*.json
          retention-days: 1

  test-10:
    name: 10-customer problems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: ["10.10.1", "10.10.2", "10.10.3", "10.10.4", "10.20.1", "10.20.2", "10.20.3", "10.20.4", "10.5.1", "10.5.2", "10.5.3", "10.5.4"]
        drone-config-mapping: ["0 0 0 0", "1 1 1 1", "2 2 2 2", "3 3 3 3"]
        energy-mode: ["linear", "non-linear", "endurance"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run optimizer (1)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-1.json" \
          --extra run-1

      - name: Run optimizer (2)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-2.json" \
          --extra run-2

      - name: Run optimizer (3)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-3.json" \
          --extra run-3

      - name: Run optimizer (4)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-4.json" \
          --extra run-4

      - name: Run optimizer (5)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-5.json" \
          --extra run-5

      - name: Run optimizer (6)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-6.json" \
          --extra run-6

      - name: Run optimizer (7)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-7.json" \
          --extra run-7

      - name: Run optimizer (8)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-8.json" \
          --extra run-8

      - name: Run optimizer (9)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-9.json" \
          --extra run-9

      - name: Run optimizer (10)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-10.json" \
          --extra run-10

      - name: Upload solutions
        uses: actions/upload-artifact@v3
        with:
          name: d2d-summary
          path: output-*.json
          retention-days: 1

  test-20:
    name: 20-customer problems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: ["20.10.1", "20.10.2", "20.10.3", "20.10.4", "20.20.1", "20.20.2", "20.20.3", "20.20.4", "20.5.1", "20.5.2", "20.5.3", "20.5.4"]
        drone-config-mapping: ["0 0 0 0", "1 1 1 1", "2 2 2 2", "3 3 3 3"]
        energy-mode: ["linear", "non-linear", "endurance"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run optimizer (1)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-1.json" \
          --extra run-1

      - name: Run optimizer (2)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-2.json" \
          --extra run-2

      - name: Run optimizer (3)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-3.json" \
          --extra run-3

      - name: Run optimizer (4)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-4.json" \
          --extra run-4

      - name: Run optimizer (5)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-5.json" \
          --extra run-5

      - name: Run optimizer (6)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-6.json" \
          --extra run-6

      - name: Run optimizer (7)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-7.json" \
          --extra run-7

      - name: Run optimizer (8)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-8.json" \
          --extra run-8

      - name: Run optimizer (9)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-9.json" \
          --extra run-9

      - name: Run optimizer (10)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-10.json" \
          --extra run-10

      - name: Upload solutions
        uses: actions/upload-artifact@v3
        with:
          name: d2d-summary
          path: output-*.json
          retention-days: 1

  test-50:
    name: 50-customer problems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: ["50.10.1", "50.10.2", "50.10.3", "50.10.4", "50.20.1", "50.20.2", "50.20.3", "50.20.4", "50.30.1", "50.30.2", "50.30.3", "50.30.4", "50.40.1", "50.40.2", "50.40.3", "50.40.4"]
        drone-config-mapping: ["0 0 0 0", "1 1 1 1", "2 2 2 2", "3 3 3 3"]
        energy-mode: ["linear", "non-linear", "endurance"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run optimizer (1)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-1.json" \
          --extra run-1

      - name: Run optimizer (2)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-2.json" \
          --extra run-2

      - name: Run optimizer (3)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-3.json" \
          --extra run-3

      - name: Run optimizer (4)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-4.json" \
          --extra run-4

      - name: Run optimizer (5)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-5.json" \
          --extra run-5

      - name: Run optimizer (6)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-6.json" \
          --extra run-6

      - name: Run optimizer (7)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-7.json" \
          --extra run-7

      - name: Run optimizer (8)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-8.json" \
          --extra run-8

      - name: Run optimizer (9)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-9.json" \
          --extra run-9

      - name: Run optimizer (10)
        run: |
          python d2d.py ${{ matrix.problem }} \
          -c ${{ matrix.drone-config-mapping }} \
          -e ${{ matrix.energy-mode }} \
          --pool-size 8 \
          --dump "output-${{ matrix.problem }}-${{ matrix.drone-config-mapping }}-${{ matrix.energy-mode }}-10.json" \
          --extra run-10

      - name: Upload solutions
        uses: actions/upload-artifact@v3
        with:
          name: d2d-summary
          path: output-*.json
          retention-days: 1

  summary:
    name: Summarize solutions
    runs-on: ubuntu-latest
    needs: [test-6, test-10, test-20, test-50]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download solutions
        uses: actions/download-artifact@v3
        with:
          name: d2d-summary
          path: d2d-summary/

      - name: Summarize solutions
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python scripts/d2d-summary.py --drone-config-mapping 1 --energy-mode 1 --extra 2

      - name: Upload summary as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: summary
          path: |
            d2d-summary/*.csv
            d2d-summary/*.png
