name: Tests

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: [a280, berlin52, bier127, d198, d493, d657, d1291, d1655, d15112]
        iterations: [200, 1500]
        tabu_size: [100, 500, 1000, 5000]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test sample 
      run: python main.py ${{ matrix.problem }} ${{ matrix.iterations }} ${{ matrix.tabu_size }}
