name: Tests

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: [a280, berlin52, bier127, ch130, ch150, eil101, eil51, eil76]
        iterations: [500, 1000, 2000]
        tabu_size: [5, 6, 7, 8, 9, 10, 500]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test sample 
      run: python main.py ${{ matrix.problem }} --iter ${{ matrix.iterations }} --tabu-size ${{ matrix.tabu_size }}
