name: Tests

on: push

permissions:
  contents: read

jobs:
  python:
    name: Run Python tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest -s
