name: Tests

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        problem: [a280, berlin52, bier127, ch130, ch150, d1291]
        iterations: [200, 400, 600, 800, 1000]
        tabu_size: [10, 50, 100, 200, 400, 800, 1000]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test sample 
      run: python main.py ${{ matrix.problem }} ${{ matrix.iterations }} ${{ matrix.tabu_size }}
