name: Tests

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run against tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: [a280, berlin52, bier127, ch150, eil101, pr144]
        iterations: [1000, 2000, 4000]
        tabu_size: [5, 10, 40]
        shuffle_after: [3, 5, 10, 100]
        exclude:
          - problem: a280
            iterations: 4000

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test sample using dx + dy distances
      run: python main.py ${{ matrix.problem }} --iter ${{ matrix.iterations }} --tabu-size ${{ matrix.tabu_size }} --shuffle-after ${{ matrix.shuffle_after }} --dump output-${{ matrix.problem }}-${{ matrix.iterations }}-${{ matrix.tabu_size }}-${{ matrix.shuffle_after }}.json

    - name: Test sample using Euclidean distances
      run: python main.py ${{ matrix.problem }} --iter ${{ matrix.iterations }} --tabu-size ${{ matrix.tabu_size }} --shuffle-after ${{ matrix.shuffle_after }} --euclide --dump output-${{ matrix.problem }}-${{ matrix.iterations }}-${{ matrix.tabu_size }}-${{ matrix.shuffle_after }}-e.json

    - name: Upload solution
      uses: actions/upload-artifact@v3
      with:
        name: summary
        path: output-**.json

  summary:
    name: Summarize solutions
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Download solutions
      uses: actions/download-artifact@v3
      with:
        name: summary
        path: summary/

    - name: View downloaded artifacts
      run: ls summary/

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Summarize solutions
      run: python summary.py

    - name: Upload CSV file
      uses: actions/upload-artifact@v3
      with:
        name: summary
        path: summary/*.csv
